version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_ENV=local
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    networks:
      - madfam-network
    restart: unless-stopped

  # Development service
  web-dev:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    networks:
      - madfam-network
    restart: unless-stopped

networks:
  madfam-network:
    driver: bridge