apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: madfam-site

resources:
- namespace.yaml
- madfam-web-deployment.yaml
- madfam-web-service.yaml
- madfam-cms-deployment.yaml
- madfam-cms-service.yaml
- network-policies.yaml
- resource-quota.yaml
- madfam-web-hpa.yaml
# secrets-template.yaml excluded — managed manually via kubectl
# Live secret has argocd.argoproj.io/sync-options: Prune=false annotation

labels:
- pairs:
    app.kubernetes.io/part-of: madfam-platform
    enclii.dev/managed-by: switchyard

images:
- digest: sha256:e88581cee3a6154e06646169f4c11d0b9934cc5098a007dad74200a4e94e455a
  name: ghcr.io/madfam-org/madfam-site/cms
  newName: ghcr.io/madfam-org/madfam-site/cms
- digest: sha256:ad4be8601fb08fd111e1a4c44774a0b221512dcd014553239edce1a48c21c3f7
  name: ghcr.io/madfam-org/madfam-site/web
  newName: ghcr.io/madfam-org/madfam-site/web
