apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: madfam-site

resources:
- namespace.yaml
- madfam-web-deployment.yaml
- madfam-web-service.yaml
- madfam-cms-deployment.yaml
- madfam-cms-service.yaml
- network-policies.yaml
- resource-quota.yaml
- madfam-web-hpa.yaml
# secrets-template.yaml excluded — managed manually via kubectl
# Live secret has argocd.argoproj.io/sync-options: Prune=false annotation

labels:
- pairs:
    app.kubernetes.io/part-of: madfam-platform
    enclii.dev/managed-by: switchyard

images:
- digest: sha256:16ded4d63d31a31d78e590ef8519860e1e03ac0e8b97fc9de49db55a3fc4879d
  name: ghcr.io/madfam-org/madfam-site/cms
  newName: ghcr.io/madfam-org/madfam-site/cms
- digest: sha256:4ee4c6739b05128233416a9bd74fd8be634260335182f5c875da54de281a7c77
  name: ghcr.io/madfam-org/madfam-site/web
  newName: ghcr.io/madfam-org/madfam-site/web
