apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: madfam-site

resources:
- namespace.yaml
- madfam-web-deployment.yaml
- madfam-web-service.yaml
- madfam-cms-deployment.yaml
- madfam-cms-service.yaml
- network-policies.yaml
- resource-quota.yaml
- madfam-web-hpa.yaml
# secrets-template.yaml excluded — managed manually via kubectl
# Live secret has argocd.argoproj.io/sync-options: Prune=false annotation

labels:
- pairs:
    app.kubernetes.io/part-of: madfam-platform
    enclii.dev/managed-by: switchyard

images:
- digest: sha256:7ed547590a02a203dd138694a748c41fc74df64a3a0aebf1656e91173196d007
  name: ghcr.io/madfam-org/madfam-site/cms
  newName: ghcr.io/madfam-org/madfam-site/cms
- digest: sha256:21461807ebe25715cd97fedd9d4e39e30f6f91ef38667c9121ddc959112d18af
  name: ghcr.io/madfam-org/madfam-site/web
  newName: ghcr.io/madfam-org/madfam-site/web
