name: Deploy to Staging (GitHub Pages)

on:
  push:
    branches: [main, staging, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test || echo "No tests configured yet"

      - name: Build for staging
        env:
          NEXT_PUBLIC_ENV: staging
          NEXT_PUBLIC_API_URL: ${{ secrets.STAGING_API_URL || 'https://staging.madfam.io/api' }}
          NEXT_PUBLIC_FEATURE_FLAGS: ${{ secrets.STAGING_FEATURES || 'staging' }}
          DEPLOY_TARGET: github-pages
        run: |
          cd apps/web
          pnpm build:staging
          # Verify static export was created
          if [ ! -d "out" ]; then
            echo "Error: Static export directory 'out' not found!"
            exit 1
          fi
          echo "Static export created successfully"
          ls -la out/

      - name: Prepare static export
        run: |
          cd apps/web
          # Add .nojekyll to prevent Jekyll processing
          touch out/.nojekyll
          # Create 404.html from index.html for client-side routing
          cp out/index.html out/404.html || echo "Note: index.html not found, skipping 404.html creation"

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/web/out