name: Deploy to Staging (GitHub Pages)

on:
  push:
    branches: [staging, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test || echo "No tests configured yet"

      - name: Build for staging
        env:
          NEXT_PUBLIC_ENV: staging
          NEXT_PUBLIC_API_URL: ${{ secrets.STAGING_API_URL }}
          NEXT_PUBLIC_FEATURE_FLAGS: ${{ secrets.STAGING_FEATURES }}
          DEPLOY_TARGET: github-pages
        run: |
          cd apps/web
          pnpm build:staging

      - name: Prepare static export
        run: |
          cd apps/web
          touch out/.nojekyll
          echo 'staging.madfam.io' > out/CNAME

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/staging'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/web/out
          cname: staging.madfam.io